# Generated by Django 3.2.5 on 2022-02-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220216_2236'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMIModel',
        ),
    ]
